### ISSUE TITLE
Make libtool happy

### ISSUE THREAD

**Issue by IngwiePhoenix** [webosbrew/meta-lg-webos-ndk#3]
Hello!

For the past few days, I have been trying to cross-compile a few programs to see what works and what does not; very much the "throw a lot at the wall and see what sticks" approach. Partially to familiarize myself more with cross compiling and to potentially find cool things that could work on my TV.

While doing so I learned one pretty important thing: `libtool`is an - excuse my french - asshole.

Basically, I was getting many instances of libtool trying to read `.la` files from my host maschine instead of the SDK. Going way, way down the rabbithole of autotools and friends, I eventually learned that at some point `--with-libtool-sysroot=` was changed to `--with-sysroot`. This alone caused an absurd amount of errors on so many levels and even more confusion. I even, in hopes of fixing that, ended up doing this: `find /opt/webos-sdk-x86_64/ -name "*.la" -print0 | xargs -0 sed -i "s#libdir='/usr/lib'#libdir='$SDKTARGETSYSROOT/usr/lib'#g"`. Yep... I ran out of ideas and options at some point. But that too did not fix my problem at all.

So I started to write an additional file for environment variables to source in and currently, this is what it says:

```
export PKG_CONFIG_PATH="/opt/webos-sdk-x86_64/1.0.g/extra/lib/pkgconfig:$PKG_CONFIG_PATH"
export PATH="/opt/webos-sdk-x86_64/1.0.g/sysroots/armv7a-neon-webos-linux-gnueabi/opt/qt5.12.12/bin/:$PATH"
export CFLAGS="-I/opt/webos-sdk-x86_64/1.0.g/sysroots/armv7a-neon-webos-linux-gnueabi/opt/qt5.12.12/include -I /opt/webos-sdk-x86_64/1.0.g/extra/include $CFLAGS"
export CXXFLAGS="$CFLAGS"
export LDFLAGS="-L/opt/webos-sdk-x86_64/1.0.g/sysroots/armv7a-neon-webos-linux-gnueabi/opt/qt5.12.12/lib -L/opt/webos-sdk-x86_64/1.0.g/extra/lib -lm $LDFLAGS"
export PREFIX=/opt/webos-sdk-x86_64/1.0.g/extra/
export CONFIGURE_FLAGS="$CONFIGURE_FLAGS --disable-shared --enable-static --with-sysroot='$SDKTARGETSYSROOT'"
```

I use the `/extras` folder to not "build/install into" the sysroot itself and keep things separated. I learned this from the [vitasdk](https://github.com/vitasdk) where locations outside the main sysroot were used in addition.

That said, I would like to request an update to the `CONFIGURE_FLAGS` env variable to save others from confusion in the future about what libtool is trying to accomplish.

Thanks for this awesome toolchain! I'm sorry if this is a little ranty, but if you burnt two days of trying to figure out why certain things are not behaving, you just end up being...a little peeved. :)

Kind regards,
Ingwie

**Comment by mariotaku** [comment]
Hi! It's so nice of you to be interested in webOS native development. I'll be checking details about this config flag, and in the meantime, did you try this one? https://github.com/openlgtv/buildroot-nc4/releases/tag/webos-9f5b1a1 It provides more modern tools, and more lightweight.

**Comment by IngwiePhoenix** [comment]
Do I use the `lgtv` or `webos` one?
Reading their device configs, they don't seem any different yet are both listed... I'll try the `webos` one first, but its still a bit confusing.

**Comment by smx-smx** [comment]
Use `lgtv` if you want to target/support both Netcast 4 and WebOS
`webos` if you just need the latter

They are only marginally different as you noticed, but the idea is to separate the default set of packages and if i remember correctly (can't check right now) the kernel headers targeted
