### ISSUE TITLE
Installing .IPK files on a rooted TV

### ISSUE THREAD

**Issue by kerta1n** [webosbrew/meta-lg-webos-ndk#4]
Hello, forgive me if I am in the wrong repository and I can close it, but how would I install an IPK file onto my system? Would the normal ares-install command work? The application I am trying to install is zopieux/lgsnapclient.

**Comment by mariotaku** [comment]
Yes. It would work for an IPK designed for webOS TV.

**Comment by kerta1n** [comment]
Just to confirm, the ares-command will not freak out if it recognizes there's no developer mode app?

**Comment by mariotaku** [comment]
No. It connects using SSH so it will be fine.

**Comment by kerta1n** [comment]
Thanks, will close
