### ISSUE TITLE
LG OLED CX is ARMV8

### ISSUE THREAD

**Issue by Zibri** [webosbrew/meta-lg-webos-ndk#5]
A version that includes also armv8 would be nice.

```
# cat /proc/cpuinfo 
processor       : 0
BogoMIPS        : 100.00
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x2
CPU part        : 0xd05
CPU revision    : 0
```

**Comment by mariotaku** [comment]
While LG uses ARM64 SoC, their rootfs is arm32 based. So ARM64 executables are not going to work on the TV unless LG fully switches to 64-bit system.

**Comment by Zibri** [comment]
You are right... My mistake... I am working on different projects and I confused this with my android phone :D
