### ISSUE TITLE
Can I use this with WebOS 22?

### ISSUE THREAD

**Issue by cscd98** [webosbrew/meta-lg-webos-ndk#6]
I want to port an C++ application to WebOS 22 (LG C2 TV). Would this be useful? has anyone else used this for such a purpose?

**Comment by mariotaku** [comment]
I think it should work for you. This NDK was used to port/develop many native programs and worked well.

**Comment by cscd98** [comment]
I noticed you linked https://github.com/openlgtv/buildroot-nc4 in the README. Is this a replacement for this ndk? Or does it provide the compilation tools only and you still need this NDK?

Where did https://github.com/openlgtv/buildroot-nc4 come from?

Thanks

**Comment by smx-smx** [comment]
Hi, buildroot-nc4 is an updated NDK (newer gcc/g++ - i.e. can use newer C++ standards, and availability to add many other packages).

This NDK remains and is also usable, but several projects have switched to the new toolchain.

**Comment by cscd98** [comment]
@smx-smx Thank you
